### PR TITLE
javascript-loops-practice by jaden bertino

### PR DESCRIPTION
**Pull request by jadenbertino**
image

### CODE REVIEW

**Comment by jadenbertino** [comment]
I know this is exercise is for loops practice, but I tried my best to use array methods whenever possible because I have less experience with them. 

Hopefully that's fine with you guys!! If not then I can change it to use loops.

**Review by scrumptiousdev — CHANGES_REQUESTED** [review]
👍🏼 Great job! I love how you used `map` and `filter`. Since you finished it quick, let's go back and convert those `map` and `filter` into loops using `for` or any other ones as a practice. Don't erase what you already have, just comment those out!

Extra point: for `sumAll` function, can you figure out with `reduce` method?

**Comment by jadenbertino** [comment]
still working on solution to `sumAll` solution with `reduce` method

**Review by scrumptiousdev — APPROVED** [review]
Approved!

**Pull request merged**
