### PR TITLE
javascript-typing-tutor by jaden bertino

### PR DESCRIPTION
**Pull request by jadenbertino**
Late PR but I added a ton of features so hopefully it was worth the wait :)
Planning to add some more features to it later also
https://user-images.githubusercontent.com/87284530/214147728-a385e9a7-ae92-4e43-afaf-6110ef4316d9.mp4

### CODE REVIEW

**Comment by jadenbertino** [comment]
Also here is the dark / light mode demo:

https://user-images.githubusercontent.com/87284530/214148538-b9a82b6e-eae5-458b-87d3-d5ee2e90b7f2.mp4

**Review by scrumptiousdev — APPROVED** [review]
👍🏼 💯 🥇 😮 🎊 🎉 🔥 🎆  Sweeeeeeeeeeeet game!!!!

**Review by kurtyazdizadeh — APPROVED** [review]
Love it! Great stuff here, I like how you're grabbing inspiration from monkeytype. Would love to see you add more features and turn this into a project for your portfolio as you learn new concepts.

Other things to keep in mind for the future (that will be covered later):

- Saving the leaderboard between page loads (session storage).
- Creating a form to collect/send results/display on leaderboard
  - (maybe create a badge that can be shared on socials), etc.

Approved 👍

**Comment by jadenbertino** [comment]
> * Saving the leaderboard between page loads (session storage).

Thanks for the suggestion! I will probably store user scores via a combo of session storage and auth via firebase if I can figure it out. 

I've worked with firebase a tiny bit but only with React so hopefully I can figure out how to do it with vanilla javascript 🤷‍♂️

**Pull request merged**
